### ISSUE TITLE
Failed while sending code!

### ISSUE THREAD

**Issue by NuraliSahatow** [saiffarooqui/SoulMate-Online-Dating-Platform#2]
When I would create new profile, site request code verifiation and show error "Failed while sending code!"
How i reapir this problem?
How to repair problem "Failed while sending code!"
Sorry my english)

**Comment by saiffarooqui** [comment]
That error is due to the failure in sending verification code.
Check controllerUserData.php from line 42,  
`if(mail($email, $subject, $message, $sender))`
The above function sends mail using SendMail.
Follow this article to configure SendMail [https://www.myonlineedu.com/blog/view/5/configure-sendmail-for-wamp-and-connect-with-gmail-in-development](url)

**Comment by NuraliSahatow** [comment]
How to disable send verification coede?\

**Comment by saiffarooqui** [comment]
You have to make changes in "controllerUserData.php" and also remove "code" field from database.
